language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
env:
  global:
    - NODE_OPTIONS=--max_old_space_size=4096s
branches:
  only:
  - master
before_script:
  - cd app
  - npm install
script:
  - echo NODE_OPTIONS
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master